### ISSUE TITLE
Instructions  on how to use it

### ISSUE THREAD

**Issue by underdog-03** [mezotv/speedtest-hide-ip#4]
Hi Dominik,
I love your page! so many interesting project 

I'm 12 years old and I'm trying to learn more. I find your project really interesting and I was wondering if I could expand on it for my learning project.

Could you help me understand how your script works and how I can use it?
I apologize if I'm a bit of a noob and a beginner :)

I also intend to add the following to your script:

[www.speedtest.net](http://www.speedtest.net/)
[www.fast.com](http://www.fast.com/)
[www.att.com/support/speedtest/](http://www.att.com/support/speedtest/)
[www.speedof.me](http://www.speedof.me/)
[www.testmy.net](http://www.testmy.net/)
[www.dslreports.com/speedtest](http://www.dslreports.com/speedtest)
speedtest.xfinity.com
https://speedtest.xfinity.com/
https://testmy.net/

Thank you so much for your help!

**Comment by mezotv** [comment]
I can recommend watching [this video](https://www.youtube.com/watch?v=0n809nd4Zu4) on how to make a chrome extention!

**Comment by underdog-03** [comment]
@mezotv Thank you for your help :)
